#!/bin/sh
if  [ $# -eq 0 ]
then 
echo "$0 : "
echo "  no arguments have been passed"
exit 1 
fi

if [ "$1" == "make" ]
then 
gcc ./ccode/main.c -o bin/main.out 
exit 1
fi

if [ "$1" == "run" ]
then 
./bin/main.out < ./data/datainput
exit 1
fi

if [ "$1" == "makecpp" ]
then
g++ -std=c++11 ./cppcode/main.cpp -o ./bin/maincpp.out
exit 1
fi

if [ "$1" == "runcpp" ]
then
./bin/maincpp.out < ./data/datainput
exit 1
fi

if [ "$1" == "librarycpp" ]
then 
sudo cp ./cppcode/neurons.cpp /usr/include/c++/5.1.1/neurons.cpp
sudo cp ./cppcode/neurons.hpp /usr/include/c++/5.1.1/neurons.hpp
exit 1
fi 

if [ "$1" == "push" ]
then 
git add --all
echo -e "\e[38;5;27m>$0 :\e[38;5;7m enter message"
read message
git commit -m "$message"
sudo git push https://github.com/dudupo/neurons.git master
exit 1
fi 