#!/bin/sh
if  [ $# -eq 0 ]
then 
echo "$0 : "
echo "  no arguments have been passed"
exit 1 
fi

if [ "$1" == "make" ]
then 
gcc ./ccode/main.c -o bin/main.out 
exit 1
fi

if [ "$1" == "run" ]
then 
./bin/main.out < ./data/datainput
exit 1
fi

if [ "$1" == "makecpp" ]
then
g++ ./cppcode/main.cpp -o ./bin/maincpp.out
exit 1
fi

if [ "$1" == "runcpp" ]
then
./bin/maincpp.out < ./data/datainput
exit 1
fi
